version: '3.7'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db 
  http:
    image: steveltn/https-portal:1
    container_name: http-blog
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
    environment:
      DOMAINS: "blog.ars-system.net -> http://web:8000/"
      STAGE: "production"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tsubota-naoki
      - POSTGRES_PASSWORD=tsubota-naoki
      - POSTGRES_DB=blog_db

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data:
