version: '3.7'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    environment:
      - CLOUD_SQL=1
    env_file:
      - ./.env
    depends_on:
      - db 
  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: 
      [
        "/cloud_sql_proxy",
        "-instances=blog-429308:us-central1:blog=tcp:0.0.0.0:5432",
        "-credential_file=/config/cloud-sql.json"
      ]
    volumes:
      - ./cloud-sql.json:/config/cloud-sql.json
    environment:
      - POSTGRES_USER=tsubota-naoki
      - POSTGRES_PASSWORD=tsubota-naoki
      - POSTGRES_DB=blog_db
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

