# Generated by Django 5.0.6 on 2024-07-10 05:55

import signup.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", signup.models.UserManager()),
            ],
        ),
    ]
