# Generated by Django 5.0.6 on 2024-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
