# Generated by Django 5.0.6 on 2024-08-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.OneToOneField(
                        default="",
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーネーム",
                    ),
                ),
            ],
        ),
    ]
