# Generated by Django 5.0.6 on 2024-08-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0004_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="UserName",
        ),
    ]
